#ifndef SRC_ZCL_ZCL_APP_THERMOSTAT_H_
#define SRC_ZCL_ZCL_APP_THERMOSTAT_H_

#define SYS_MODE_OFF            0x00
#define SYS_MODE_AUTO           0x01
#define SYS_MODE_COOL           0x03
#define SYS_MODE_HEAT           0x04
#define SYS_MODE_EMERGENCY      0x05
#define SYS_MODE_PRECOOLING     0x06
#define SYS_MODE_FAN            0x07
#define SYS_MODE_DRY            0x08
#define SYS_MODE_SLEEP          0x09

#define RUN_MODE_OFF            0x00
#define RUN_MODE_COOL           0x03
#define RUN_MODE_HEAT           0x04

#define RUN_STATE_HEAT_BIT      0

#define MANUAL_MODE             0x00
#define PROG_MODE               0x01

#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SENSOR_USED                   0xF000
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_HOUR_1           0xF001
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_MINUTE_1         0xF002
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_TEMPERATURE_1    0xF003
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_HOUR_2           0xF004
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_MINUTE_2         0xF005
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_TEMPERATURE_2    0xF006
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_HOUR_3           0xF007
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_MINUTE_3         0xF008
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_TEMPERATURE_3    0xF009
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_HOUR_4           0xF00a
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_MINUTE_4         0xF00b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_TEMPERATURE_4    0xF00c
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_HOUR_5           0xF00d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_MINUTE_5         0xF00e
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_TEMPERATURE_5    0xF00f
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_HOUR_6           0xF010
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_MINUTE_6         0xF011
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_MON_TEMPERATURE_6    0xF012

#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_HOUR_1           0xF013
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_MINUTE_1         0xF014
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_TEMPERATURE_1    0xF015
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_HOUR_2           0xF016
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_MINUTE_2         0xF017
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_TEMPERATURE_2    0xF018
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_HOUR_3           0xF019
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_MINUTE_3         0xF01a
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_TEMPERATURE_3    0xF01b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_HOUR_4           0xF01c
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_MINUTE_4         0xF01d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_TEMPERATURE_4    0xF01e
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_HOUR_5           0xF01f
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_MINUTE_5         0xF020
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_TEMPERATURE_5    0xF021
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_HOUR_6           0xF022
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_MINUTE_6         0xF023
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_TUE_TEMPERATURE_6    0xF024

#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_HOUR_1           0xF025
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_MINUTE_1         0xF026
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_TEMPERATURE_1    0xF027
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_HOUR_2           0xF028
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_MINUTE_2         0xF029
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_TEMPERATURE_2    0xF02a
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_HOUR_3           0xF02b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_MINUTE_3         0xF02c
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_TEMPERATURE_3    0xF02d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_HOUR_4           0xF02e
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_MINUTE_4         0xF02f
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_TEMPERATURE_4    0xF030
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_HOUR_5           0xF031
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_MINUTE_5         0xF032
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_TEMPERATURE_5    0xF033
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_HOUR_6           0xF034
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_MINUTE_6         0xF035
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_WED_TEMPERATURE_6    0xF036

#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_HOUR_1           0xF037
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_MINUTE_1         0xF038
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_TEMPERATURE_1    0xF039
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_HOUR_2           0xF03a
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_MINUTE_2         0xF03b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_TEMPERATURE_2    0xF03c
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_HOUR_3           0xF03d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_MINUTE_3         0xF03e
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_TEMPERATURE_3    0xF03f
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_HOUR_4           0xF040
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_MINUTE_4         0xF041
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_TEMPERATURE_4    0xF042
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_HOUR_5           0xF043
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_MINUTE_5         0xF044
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_TEMPERATURE_5    0xF045
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_HOUR_6           0xF046
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_MINUTE_6         0xF047
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_THU_TEMPERATURE_6    0xF048

#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_HOUR_1           0xF049
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_MINUTE_1         0xF04a
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_TEMPERATURE_1    0xF04b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_HOUR_2           0xF04c
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_MINUTE_2         0xF04d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_TEMPERATURE_2    0xF04e
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_HOUR_3           0xF04f
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_MINUTE_3         0xF050
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_TEMPERATURE_3    0xF051
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_HOUR_4           0xF052
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_MINUTE_4         0xF053
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_TEMPERATURE_4    0xF054
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_HOUR_5           0xF055
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_MINUTE_5         0xF056
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_TEMPERATURE_5    0xF057
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_HOUR_6           0xF058
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_MINUTE_6         0xF059
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_FRI_TEMPERATURE_6    0xF05a

#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_HOUR_1           0xF05b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_MINUTE_1         0xF05c
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_TEMPERATURE_1    0xF05d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_HOUR_2           0xF05e
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_MINUTE_2         0xF05f
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_TEMPERATURE_2    0xF060
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_HOUR_3           0xF061
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_MINUTE_3         0xF062
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_TEMPERATURE_3    0xF063
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_HOUR_4           0xF064
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_MINUTE_4         0xF065
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_TEMPERATURE_4    0xF066
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_HOUR_5           0xF067
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_MINUTE_5         0xF068
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_TEMPERATURE_5    0xF069
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_HOUR_6           0xF06a
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_MINUTE_6         0xF06b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SAT_TEMPERATURE_6    0xF06c

#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_HOUR_1           0xF06d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_MINUTE_1         0xF06e
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_TEMPERATURE_1    0xF06f
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_HOUR_2           0xF070
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_MINUTE_2         0xF071
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_TEMPERATURE_2    0xF072
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_HOUR_3           0xF073
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_MINUTE_3         0xF074
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_TEMPERATURE_3    0xF075
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_HOUR_4           0xF076
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_MINUTE_4         0xF077
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_TEMPERATURE_4    0xF078
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_HOUR_5           0xF079
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_MINUTE_5         0xF07a
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_TEMPERATURE_5    0xF07b
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_HOUR_6           0xF07c
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_MINUTE_6         0xF07d
#define ZCL_ATTRID_HVAC_THERMOSTAT_CUSTOM_SCHEDULE_SUN_TEMPERATURE_6    0xF07e

//typedef enum {
//    SENSOR_IN   =   0x00,
//    SENSOR_AL,
//    SENSOR_OU
//} sensor_used_t;

typedef enum {
    DAY_SUN = 0x00, // Sunday
    DAY_MON = 0x01, // Monday
    DAY_TUE = 0x02, // Tuesday
    DAY_WED = 0x03, // Wednesday
    DAY_THU = 0x04, // Thursday
    DAY_FRI = 0x05, // Friday
    DAY_SAT = 0x06  // Saturday
} day_of_week_t;


uint8_t zcl_convert_temperature_fromCtoF(int16_t tempC);
int16_t zcl_convert_temperature_fromFtoC(int16_t tempF);

#endif /* SRC_ZCL_ZCL_APP_THERMOSTAT_H_ */
